### ISSUE TITLE
在Viewpager2中使用该库，addData时会空指针崩溃

### ISSUE THREAD

**Issue by GiveMeTheMoney** [lihangleo2/ViewPager2Demo#11]
Viewpager2中的fragment使用SmartViewPager2Adapter，初始化时正常，接口获取数据后，addData时会空指针崩溃
初始化：private val mAdapter by lazy {
        SmartViewPager2Adapter.Builder<IndexListBean>(this)
            .overScrollNever()
            .setOffscreenPageLimit(10)
            .setPreLoadLimit(5)
            .addFragment(1, GirlShowVideoFragment::class.java)
            .addFragment(2, GirlShowVoiceFragment::class.java)
            .addFragment(3, GirlShowImageFragment::class.java)
            .build(mBinding.viewPager2)
    }
          
接口获取数据后addData报错
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
                 	at com.xiangyu.base.model.IndexListBean.hashCode(Unknown Source:19)
                 	at com.smart.adapter.SmartViewPager2Adapter.getItemId(SmartViewPager2Adapter.kt:396)
                 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6827)
                 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
                 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
                 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
                 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
                 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
                 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
                 	at android.view.View.layout(View.java:24447)
                 	at android.view.ViewGroup.layout(ViewGroup.java:6667)
                 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
                 	at android.view.View.layout(View.java:24447)
                 	at android.view.ViewGroup.layout(ViewGroup.java:6667)
                 	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
                 	at android.view.View.layout(View.java:24447)
                 	at android.view.ViewGroup.layout(ViewGroup.java:6667)
                 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
                 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                 	at android.view.View.layout(View.java:24447)
                 	at android.view.ViewGroup.layout(ViewGroup.java:6667)
                 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407)
                 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
                 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
                 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
                 	at android.view.View.layout(View.java:24447)
                 	at android.view.ViewGroup.layout(ViewGroup.java:6667)
                 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
                 	at android.view.View.layout(View.java:24447)
                 	at android.view.ViewGroup.layout(ViewGroup.java:6667)
                 	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
                 	at android.view.View.layout(View.java:24447)
                 	at android.view.ViewGroup.layout(ViewGroup.java:6667)
                 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
                 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                 	at android.view.View.layout(View.java:24447)
                 	at android.view.ViewGroup.layout(ViewGroup.java:6667)
                 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407)
                 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
                 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
                 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)

**Comment by GiveMeTheMoney** [comment]
即使不嵌套使用，在Activity中单独使用SmartViewPager2Adapter，同样是在addData时会空指针崩溃，报错日志一样

**Comment by GiveMeTheMoney** [comment]
是数据源对象的问题导致的，改了一下结构解决了，虽然不知道为啥=。=
