### ISSUE TITLE
当页面被系统恢复重新创建对象，导致奔溃

### ISSUE THREAD

**Issue by zt174499006** [lihangleo2/ViewPager2Demo#5]
打开，系统恢复，或者旋转，又或者折叠切换屏幕。
 java.lang.IllegalStateException: Design assumption violated.
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:287)
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:276)
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7867)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:893)
                                                                                                    	at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)

**Comment by zt174499006** [comment]
暂时用setSaveEnabled，解决了，希望对其他人有帮助

**Comment by lihangleo2** [comment]
非常感谢你的提问，问题已经解决了。
