### ISSUE TITLE
反复进入和退出二级页面，会导致一级页面FragmentStateAdapter 执行异常

### ISSUE THREAD

**Issue by zt174499006** [lihangleo2/ViewPager2Demo#7]
024-01-18 21:30:33.954 31543-31543 createFragment          com.posher.kmeta                     E  +++++++++++++++++++++++++++++  createFragment0
2024-01-18 21:30:33.956  3280-3846  ActivityManagerWrapper  pid-3280                             E  getRecentTasks: mainTaskId=47796   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.posher.kmeta/com.posher.kmeta.page.login.SplashActivity} }
2024-01-18 21:30:33.962 31543-31543 AndroidRuntime          com.posher.kmeta                     D  Shutting down VM
2024-01-18 21:30:33.963 31543-31543 AndroidRuntime          com.posher.kmeta                     E  FATAL EXCEPTION: main
                                                                                                    Process: com.posher.kmeta, PID: 31543
                                                                                                    java.lang.IllegalStateException: Design assumption violated.
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:287)
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:276)
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7867)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:893)
                                                                                                    	at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8902)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8860)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8848)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1645)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
2024-01-18 21:30:33.963 31543-31543 AndroidRuntime          com.posher.kmeta                     E  	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1655)
                                                                                                    	at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1509)
                                                                                                    	at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1417)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
2024-01-18 21:30:33.963 31543-31543 AndroidRuntime          com.posher.kmeta                     E  	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at com.android.internal.policy.DecorView.onLayout(DecorView.java:874)
                                                                                                    	at android.view.View.layout(View.java:23950)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6492)
                                                                                                    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4230)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3598)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2556)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9508)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1467)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1003)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1435)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8401)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
2024-01-18 21:30:33.964  3280-3846  ActivityManagerWrapper  pid-3280                             E  getRecentTasks: mainTaskId=47796   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608

**Comment by lihangleo2** [comment]
1、我自测的时候，模仿页面被异常杀死再恢复都没事，你可以试着把当前页面进行横竖屏切换。
2、而且看报错，你触发了我的log:024-01-18 21:30:33.954 31543-31543 createFragment com.posher.kmeta E +++++++++++++++++++++++++++++ createFragment0，你退出2级页面怎么会引1级页面index =0 重建，项目里是否存在不合规操作，比如删除了bean对象
3、是什么版本引起的，是否用的是最新版本3.0.0
4、如果以上没思路，你可以运行demo工程，去模拟你的应用场景，如果确定了是框架问题，请重新打开这个issue

**Comment by zt174499006** [comment]
被你提醒，我知道具体大概原因了，我再父级页面套用ViewPager2 ，在viewpage2里使用你组件，进入其他页面时都会重新执行createFragment0方法，估计这样就是导致直接闪退原因
2024-01-19 11:51:28.863 25879-25879 createFragment          com.posher.kmeta                     E  +++++++++++++++++++++++++++++  createFragment0
2024-01-19 11:51:28.863  3280-3846  ActivityManagerWrapper  pid-3280                             E  getRecentTasks: mainTaskId=47919   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{com.posher.kmeta/com.posher.kmeta.page.login.SplashActivity} }
2024-01-19 11:51:28.921 25879-25879 createFragment          com.posher.kmeta                     E  +++++++++++++++++++++++++++++  createFragment1
2024-01-19 11:51:28.976 25879-25879 createFragment          com.posher.kmeta                     E  +++++++++++++++++++++++++++++  createFragment2

**Comment by chenchangrong** [comment]
> 被你提醒，我知道具体大概原因了，我再父级页面套用ViewPager2 ，在viewpage2里使用你组件，进入其他页面时都会重新执行createFragment0方法，估计这样就是导致直接闪退原因 2024-01-19 11:51:28.863 25879-25879 createFragment com.posher.kmeta E +++++++++++++++++++++++++++++ createFragment0 2024-01-19 11:51:28.863 3280-3846 ActivityManagerWrapper pid-3280 E getRecentTasks: mainTaskId=47919 userId=0 baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{com.posher.kmeta/com.posher.kmeta.page.login.SplashActivity} } 2024-01-19 11:51:28.921 25879-25879 createFragment com.posher.kmeta E +++++++++++++++++++++++++++++ createFragment1 2024-01-19 11:51:28.976 25879-25879 createFragment com.posher.kmeta E +++++++++++++++++++++++++++++ createFragment2

我也遇到了这种情况，不知道该如何解决，Viewpager2 下的fragment又使用了该组件SmartViewpager2，滑动后出现崩溃

**Comment by chenchangrong** [comment]
看了源码查了资料，说是重写了getItemId()时，也要重写containsItems()方法，不然就不要重写getItemId
